### ISSUE TITLE
Highlighting config conflicts with default Sublime Text highlight settings

### ISSUE THREAD

**Issue by Osspial** [rust-lang/sublime-rust#106]
Both the default syntax highlighting and the highlighting included in this package are named `Rust`, leading to a naming conflict where the built-in highlights take priority. Because they are named the same, any attempts to rebind back to the highlights included in this package fail. This could probably be fixed by renaming these highlights to "Rust Enhanced", removing the naming conflict.

**Comment by dashed** [comment]
I just ran into this problem. 

Add the following into your `Preferences.sublime-settings` file:

```js
{
    // ....
    "ignored_packages":
    [
        "Rust",
        
       // ...
    ],

    // ...
}
```

I found how to do this via: http://www.tomhartwig.nl/blog/sublime-text-2-remove-syntaxes/

**Comment by Jayflux** [comment]
@Osspial @dashed  this should no longer be the case now the name change has gone into package control:
https://github.com/wbond/package_control_channel/pull/5865
https://packagecontrol.io/packages/Rust%20Enhanced

Are you still seeing this problem, even with the Rust package out of ignored packages?
Packages from package control should override the built-in ones.

**Comment by Osspial** [comment]
@Jayflux The issue isn't the package name, it's the name of the syntax highlighting file. As you can see here, the name is the same, so there's a conflict which the default package wins.
![highlights](https://cloud.githubusercontent.com/assets/16296823/19944385/187ce8fa-a112-11e6-9c02-57a1c7414330.png)

**Comment by Jayflux** [comment]
@Osspial  Yup, that's expected.
Its complicated, basically i had to wait for Package control to accept my changes first (which they have done now).
Now that my changes have gone in, i have done a new release https://github.com/rust-lang/sublime-rust/releases/tag/v1.0.0
This enables me to make syntax highting changes without breaking ST2.
It will take around an hour or 2 for the changes to propogate, but in theory, the Rust name should change to Rust Enhanced once Sublime pulls down the update

**Comment by Jayflux** [comment]
@Osspial also could you tell me your sublime text version?

**Comment by Osspial** [comment]
@Jayflux I'm running Sublime Text 3 build 3126

**Comment by Jayflux** [comment]
@Osspial it should have propagated now give it a try.
run package control: upgrade

**Comment by dashed** [comment]
After restarting Sublime Text, I can confirm that the package auto-updated to "Rust Enhanced" on my end 👍

**Comment by Jayflux** [comment]
ok thanks @dashed  i'm closing this issue.
