### ISSUE TITLE
No highlighting for tests

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang/sublime-rust#107]
The feature mentioned [here](https://github.com/rust-lang/sublime-rust#cargo-tests-with-highlighting) doesn't work for me. I get just a plain text.

Gentoo Linux, Sublime 3126, Rust Enhanced 0.1.0

**Comment by Jayflux** [comment]
@RazrFalcon I have Gentoo installed,  but im not sure how to install Sublime Text

**Comment by RazrFalcon** [comment]
Hi. Looks like it fixed after updating to v1.0.0. I'm closing it.
