### ISSUE TITLE
Support .cargo/config in project directory

### ISSUE THREAD

**Issue by AndyBarron** [rust-lang/sublime-rust#109]
I have a `.cargo/config` that enables incremental compilation. AFAICT, this is ignored when building from Sublime.

**Comment by AndyBarron** [comment]
Quick update: It looks like it actually did work, but since I enabled `-Zincremental=.cache` and worked on a file in the `src/` directory, it created `src/.cache` rather than `.cache` in crate root. So maybe `cargo` is called from the wrong working directory?

**Comment by Jayflux** [comment]
@AndyBarron from what i can see, cargo is called from the file you build from.
So this should be the same as going to that directory in the command line and running ```cargo build```
@dten ?

**Comment by AndyBarron** [comment]
Yes. I think there is additional value to building from the crate root; I would imagine that more complex project configuration options would use paths relative to the root. Such projects would break when building from Sublime!

**Comment by Jayflux** [comment]
@AndyBarron do you have this project on github anywhere so we can try it?
