### ISSUE TITLE
Highlighting breaks on generics over arrays

### ISSUE THREAD

**Issue by Osspial** [rust-lang/sublime-rust#110]
When having generics over arrays, the type name doesn't get highlighted, the left pointy bracket isn't colored, and the opening bracket of the array gets an error highlight. They should be highlighted as the regular generic highlight.

![arraygenerics](https://cloud.githubusercontent.com/assets/16296823/19985042/371c3a42-a1e7-11e6-959a-aed9f6e7cfe1.png)

**Comment by crumblingstatue** [comment]
Is this bug really fixed? I'm using Rust Enhanced v1.3.2, and even this exact code still triggers the error highlight.

**Comment by dten** [comment]
hi @Osspial i'm not seeing the same problem
![image](https://cloud.githubusercontent.com/assets/1019038/26621598/37cdccb6-45df-11e7-9424-51a86a60460a.png)

**Comment by crumblingstatue** [comment]
Okay, so actually, the `Rust enhanced` syntax highlighting doesn't have this problem.

Now I realized that there are two options for highlighting. `Rust`, and `Rust Enhanced`, and the default is `Rust`. Is this normal? The readme says "It should override the default Rust within Sublime", so I'm guessing not. Any way to make it the default?

**Comment by dten** [comment]
There are some issues caused by there being two. Easiest fix is to `Disable Package` -> `Rust`
