### ISSUE TITLE
Sublime Text opens empty non-existent file when error originates in macro

### ISSUE THREAD

**Issue by Boscop** [rust-lang/sublime-rust#111]
Whenever an error is caused by a derive macro, sublime opens a non-existent file with the name of the macro when pressing F4 to jump to the error:
E.g.
```
error[E0412]: type name `Foo` is undefined or not in scope
 --> <proc-macro source code>:1:4261
```
When I press F4 it opens a new empty file named <proc-macro source code>. This is undesirable.
Btw, in this case the error was caused by using #[derive(Serialize)] on an enum with a member that uses an undefined type:
```
#[derive(Serialize, Deserialize)]
pub enum Bar {
	Bla(Foo),
}
```

**Comment by dten** [comment]
Is this still the case after the recent changes from https://github.com/rust-lang/sublime-rust/pull/104
the current macro does not match the example you gave
https://regex101.com/r/Rj3dFS/1

**Comment by Boscop** [comment]
Hm, how can I know which version of the plugin I have?
Before this I did Ctrl-P, Update Package, Rust..

**Comment by dten** [comment]
If you do

ctrl shift p
List packages

It should show Rust Enhanced v1.0.0

**Comment by Boscop** [comment]
Weird. It shows v0.1.0. Why didn't it update?

**Comment by dten** [comment]
Don't know. Ctrl + ' will show the console (probably) which might have a message from package control

Oh are you using sublime 3? The plugin no longer supports 2

**Comment by Boscop** [comment]
Yes, I have sublime 3. I updated the package again, now it lists V1.0.0, but it stopped highlighting the syntax, all rust code is white now. I restarted Sublime, still no syntax highlighting! I closed the file and reopened it, still no syntax highlighting, what should I do?

**Comment by dten** [comment]
The plugin renamed to stop confusion with the base Rust package. Personally I disable the base Rust one. You'll probably have to reselect the syntax for rs files and then all should be well.

**Comment by Boscop** [comment]
Yes, I mean it lists Rust Enhanced v1.0.0. 
I have Rust Enhanced, RustAutoComplete and SublimeLinter-contrib-rustc
Do I have to edit some config file to assign Rust syntax to .rs files?

**Comment by Boscop** [comment]
In the lower right menu where one can choose syntax, Rust doesn't even appear anymore, why?

**Comment by dten** [comment]
Just ctrl shift p and set syntax to rust. If you have the base plugin also there might be two in the list still. It's still a bit confusing.

This plugin doesn't do auto complete yet

**Comment by dten** [comment]
Just double checked the syntax should show as Rust Enhanced

**Comment by Boscop** [comment]
It doesn't show up!
![](http://i.imgur.com/xV6X1TU.png)

**Comment by dten** [comment]
Can you check the console output for messages about the rust packages. Just check also that Rust Enhanced didn't accidentally get disabled

**Comment by Boscop** [comment]
It says it loaded it, how can I check if it's disabled?
```
...
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Rust Enhanced.SyntaxCheckPlugin
reloading plugin RustAutoComplete.RustAutoComplete
reloading plugin RustAutoComplete.tests
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-contrib-rustc.linter
SublimeLinter: rust linter loaded 
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin Terminal.Terminal
plugins loaded
SublimeLinter: debug mode: off 
```

**Comment by Boscop** [comment]
Ok, I did Ctrl-shift-P, enable package, it only listed 'vintage' as package that could be enabled.
So I did Ctrl-shift-P, disable package, it listed Rust Enhanced, I did that and then re-enabled it, and restarted Sublime. But still the Rust syntax doesn't show up!

**Comment by dten** [comment]
Those messages imply it's enabled and loaded. Not sure why it would not be showing. Can only suggest turn it off and on again.

**Comment by dten** [comment]
Try one step up. Remove and install package?

**Comment by Boscop** [comment]
Ok, I did that, uninstalled, reinstalled, restarted Sublime. Still the syntax doesn't show up?
What can I do now?

**Comment by dten** [comment]
What build of 3 do you have installed?

**Comment by Boscop** [comment]
3083

**Comment by dten** [comment]
Ahbthats it. You'll have to update. 3103 added a new syntax format and v1 of this plugin uses that now.

**Comment by Boscop** [comment]
Ah thanks! I updated now, should I choose syntax Rust or Rust Enhanced now?

**Comment by dten** [comment]
Rust enhanced is this plugin.
Rust is the one that now comes with sublime and is just a simpler version of this one.

I disable Rust and let the enhanced one cover everything

**Comment by Boscop** [comment]
Ok, I disabled the package 'Rust' too now. Thanks a lot!
