### ISSUE TITLE
One-line Comment highlighting fails when previous line ends with open parens

### ISSUE THREAD

**Issue by Boscop** [rust-lang/sublime-rust#112]
In this code, the comment is highlighted like code:
![](http://i.imgur.com/V1p9K38.png)
If you remove the '(', it gets highlighted as a comment.

Also this:
![](http://i.imgur.com/LuNSmn3.png)

**Comment by Boscop** [comment]
Also this:
![](http://i.imgur.com/2yqSNlL.png)

**Comment by Jayflux** [comment]
i think @dten has fixed this so closing

**Comment by Jayflux** [comment]
Fixed in v1.0.1
https://github.com/rust-lang/sublime-rust/releases/tag/v1.0.1
