### ISSUE TITLE
Highlighting is inconsistent

### ISSUE THREAD

**Issue by Boscop** [rust-lang/sublime-rust#113]
Highlighting is inconsistent. Here is an example image:
![](http://i.imgur.com/M2TK64r.png)
E.g.:
- Keywords like impl are blue, but pub and for and unsafe are red. But struct and enum and mod are blue
- Enum cases are blue, but the enum name is white
- Self is blue but Output is white. 
- self and other are orange in the function signature, but white in the body. It makes it harder for the eye to associate them.
- #[] has the same color as comments, but it is not meaningless.
- Function names are green when declared, even closures, but blue when called
- in MidiMessage, u8 and f64 have different colors, also in MsgServerToClient JoinError and PlayerId have different colors.

Consistency is very important to quickly see what's going on in the code, inferring what everything is.

I propose this color scheme:
- All keywords red, also trait, struct, enum, impl, fn
- Type names, incl. associated type names and type args like T, trait names and method names and enum case names blue. (Self should stay blue because it's a type name)
- function names, closure names, function pointer variable names should all have the same color in definition, declaration and call contexts. E.g. green. If it's too much effort to parse/detect that they are callables, they should all be white like variables.
- #[] things should be orange, instead of function args, to distinguish them visually from comments
- operators should be red too, like dot for method calling and <>, also comma, semicolon, colon and ->, ::, but braces, brackets and parens should stay white.
- Variables always white but Type variables blue.
- Constants always purple: ![](http://i.imgur.com/tO3an1B.png)

Here is an example:
![](http://i.imgur.com/2bgluXG.png)
- blue: KeyCode, VirtualKeyCode, Service, Channel, T, In, Out, E,D,S,F, Option
- red: enum, impl, ::, :, ->, ;, trait, struct, <, >, fn, comma
- key should be white in both cases

In the first example above: BitOr, Ignore, Output, MidiMessage should be blue, self, rhs, other should be white, transmute should be the same color as bitor and contains (green). #[repr(u8)], #[inline(always)] and derive should be orange.

What do you think?

**Comment by petrochenkov** [comment]
This is the first thing I noticed after all these plugin reforms started :(
When [implementing the previous coloring scheme](https://github.com/rust-lang/sublime-rust/pull/65) I audited everything at once and tried pretty carefully to be consistent in coloring of types, values, calls, punctuation, etc.
It seems like that coloring scheme was completely scrapped when `.sublime-syntax` was introduced, and I'm not sure what principles is the new scheme built on.
Good thing is that I don't use Sublime now, so I don't have to endure looking at all this mess 😄

**Comment by Boscop** [comment]
Good to know I'm not the only one who thinks consistent highlighting is important. (Btw, I tried Jetbrains but it had other issues..)

**Comment by dten** [comment]
@wbond redid the syntax

The colour itself is not something the plugin decides directly but it definitely has some bugs at the moment

**Comment by dten** [comment]
http://www.sublimetext.com/docs/3/scope_naming.html

Explains some choices. I hadn't noticed this doc though so I'll see how it compares.

**Comment by Jayflux** [comment]
@Boscop is this still a problem with the latest 1.3.0 version? There's been some syntax updates since this bug was raised.

If so could you update the ticket against that version so we can see what's still outstanding?
For some things, like fn being red, we won't be able to change now, see the conversation in  https://github.com/rust-lang/sublime-rust/pull/116 for why that is

Thanks
