### ISSUE TITLE
Matching braces fails

### ISSUE THREAD

**Issue by Boscop** [rust-lang/sublime-rust#114]
Matching braces often fails, e.g.:
![](http://i.imgur.com/41ynSft.png)
![](http://i.imgur.com/Pxqq0Sa.png)

**Comment by dten** [comment]
I have tested the cases you posted with fixed syntax and latest sublime and all was well.

**Comment by Jayflux** [comment]
Fixed in v1.0.1
https://github.com/rust-lang/sublime-rust/releases/tag/v1.0.1
