### ISSUE TITLE
Allow skipping warnings when jumping to error

### ISSUE THREAD

**Issue by Boscop** [rust-lang/sublime-rust#117]
When the output has warnings such as `warning[E0122]: trait bounds are not (yet) enforced in type definitions` that cannot be disabled, it's annoying that F4 jumps to the warning instead of the first error.
It should be possible to skip warnings and jump to the next error with F4.

**Comment by dten** [comment]
This isn't something a simple build system can do I think. Since this is a very specific warning and normally you can allow others by scope wouldn't it make more sense to request to rust to make it disableable?

**Comment by Jayflux** [comment]
You can now hide warning, also we can switch warnings off for the post-save feature too.
Closing this, please raise an issue if its still a problem
