### ISSUE TITLE
Add  command or hotkey to enable/disable syntax checking

### ISSUE THREAD

**Issue by andrii-zymohliad** [rust-lang/sublime-rust#121]
Syntax checking feature works great and is very useful. I've never seen something similar in Sublime Text. But during writing code it is also very distracting, pointing to unfinished parts as an errors. And it's not very convenient to change the setting ```rust_syntax_checking``` every time.

So I propose to have a special command-palette command to switch the state of syntax checking.

**Comment by andrii-zymohliad** [comment]
I'm trying to do it by myself. I don't have any experience in hacking Sublime Text, so i'm not sure if i'm doing everything correct.
I created file `Rust.sublime_commands` with following content:
```
[
    { 
        "caption": "Rust: Toggle syntax checking", 
        "command": "toggle_setting", 
        "args": {
            "setting": "rust_syntax_checking",
        }
    }
]
```
Setting is really toggled, as I see using `view.settings().get('rust_syntax_checking')` in console, but anyway I can't disable syntax checking without restarting Sublime Text. Is there a simple way to make it work?

**Comment by Jayflux** [comment]
@andrii-zymohliad do you have a branch/fork anywhere for me to see your attempt?

**Comment by andrii-zymohliad** [comment]
@Jayflux wow, so quick response with PR! 
Can anybody please give me a hint how to install ST plugin from sources? Sorry for stupid question, I can't find it in readme or in ST documentation. I tried to copy directory with sources to ~/.config/sublime-text-3/Packages/, but it doesn't seem to work.

**Comment by andrii-zymohliad** [comment]
@Jayflux it works for me.

**Comment by Jayflux** [comment]
@andrii-zymohliad this has now been released
https://github.com/rust-lang/sublime-rust/releases/tag/v1.0.2
