### ISSUE TITLE
Failures in syntax_test_rust.rs

### ISSUE THREAD

**Issue by Jayflux** [rust-lang/sublime-rust#125]
https://gist.github.com/Jayflux/0e660fd525fee1beca638f53876b4916

@dten is this something you know about?

**Comment by dten** [comment]
Think they came from your tweaks between taking the file from SublimePackages and adding it here. I think...
I'm going to do a different branch that improves the syntax stuff without going against the sublime future soon

**Comment by Jayflux** [comment]
@dten you  think it would be possible to run the syntax checks on PR somewhere? 
May need to chat to you on irc or something about it

**Comment by dten** [comment]
@wbond is it possible to automate the syntax tests? PackageControl doesn't seem to

**Comment by wbond** [comment]
Not currently, no. The syntax highlighting engine is used for the tests, and it is not available outside of the Sublime Text executable. Mostly this is due to the work it would take to extract it into a standalone executable. It has been requested by a couple of users, but for now the tests have to be run by hand.

**Comment by dten** [comment]
thanks for the confirmation. we'll just have to be diligent

**Comment by wbond** [comment]
In the case of default packages, the tests are run as part of building Sublime Text, so we definitely catch anything before a new build goes out. That obviously doesn't help for third-party packages, however.

**Comment by wbond** [comment]
Sorry, I commented on the closed PR before, should have gone here.

At https://github.com/sublimehq/Packages/commit/b69477be90811ad2b248bd5e36b4774aea8ae892 I ported the new tests that were added. Currently all of the tests pass there.

I'm planning on brining the scopes more in line with http://www.sublimetext.com/docs/3/scope_naming.html in the near future. The Rust syntax was somewhat early in the process of me getting familiar with the existing landscape of scope names, so some of them deviate from what we've now established as guidelines.

**Comment by Jayflux** [comment]
I've just checked these tests agaiun and they're passing now. I think its because we changed the name of the package and it was testing against the wrong file!

When i change the top line to `// SYNTAX TEST "Packages/sublime-rust/RustEnhanced.sublime-syntax"` i now get `Success: 2565 assertions in 1 files passed`
