### ISSUE TITLE
The context menu to open the settings file is looking in the wrong path

### ISSUE THREAD

**Issue by ark-** [rust-lang/sublime-rust#128]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
1.0.2

### Operating system
OS Name	Microsoft Windows 7 Pro
Version	6.1 Build 7601

### Expected behavior
The settings file should open from the contect menu

### Actual behavior
A blank file is opened at the wrong path (see next section for details)

### Steps to reproduce
1. In the menu bar, click `Preferences > Package Settings > Rust > Settings - User`
2. An attempt to open settings file under the old name `<package directory>/Packages/Rust/Rust.sublime-settings`
3. Should be opening`<package directory>/Packages/Rust Enhanced/Rust.sublime-settings`

### References
N/A

### Considerations
Has this name change affected other functionality

**Comment by Jayflux** [comment]
This is now fixed (hopefully) in release 1.1.0
