### ISSUE TITLE
"Build" calls rustc rather than cargo

### ISSUE THREAD

**Issue by joliss** [rust-lang/sublime-rust#143]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
1.1.1

### Operating system
OS Name	macOS
Version	10.12.3

### Description

Pressing Cmd+Shift+P and selecting "Build With: RustEnhanced" calls `rustc`, rather than `cargo`.

I'm getting the following output in the bottom pane:

```
error[E0463]: can't find crate for `rustc_serialize`
 --> /net/sujin/home/ubuntu/src/rust-playground/src/ohai.rs:1:1
  |
1 | extern crate rustc_serialize;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

[Finished in 0.4s with exit code 101]
[shell_cmd: rustc /net/sujin/home/ubuntu/src/rust-playground/src/ohai.rs]
[dir: /net/sujin/home/ubuntu/src/rust-playground/src]
[path: /Users/primary/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/primary/bin]
```

Note that the `shell_cmd` says `rustc`. As a result of using `rustc`, it fails to find the external crates we are using.

I believe it should call `cargo` instead. The `cargo` binary is in the search path at `/Users/primary/.cargo/bin/cargo`, so I'm not sure why it's not working.

If I select Tools -> Build System -> RustEnhanced, and then Tools -> Build, the same thing happens.

If I select Tools -> Build System -> Rust, and then Tools -> Build, the same thing happens.

If I select Tools -> Build System -> Automatic, and then Tools -> Build, it does call `cargo`, but it doesn't show build errors in the source code, so I'm having to hunt for line numbers. (I'm not sure if that's calling the built-in Rust or the RustEnhanced plugin.)

**Comment by LukeSkyw** [comment]
Same thing here. Cargo is not in the command palette.
I double checked and `rustc` and `cargo` are accessible from my shell from which I launch sublime. Not error message in sublime's console.
Something seems broken.

**Comment by dten** [comment]
Is Cargo a choice in Tools -> Build System?

**Comment by LukeSkyw** [comment]
Went back to have a look to answer you and now cargo is there, weird...
Besides, live syntax checking works, but erratically. When I save main.rs the error message disappear, I have to save other files in the project for the messages to come back (?)
Thanks @dten.

**Comment by dten** [comment]
There are some chnages in an upcoming PR that improve errors on save.

As for this issue it all sounds like intended. The there's build with Rust which uses rustc and there's build with Cargo which uses cargo

Both appear in the command pallette when automatic is selected

**Comment by joliss** [comment]
Yes, I have *two* Cargo entries in Tools -> Build System. They both seem to work fine.

Now when I select "Automatic" as the Build System it works as well. I'm not sure if it worked originally or if something changed in the meantime.

In any case, I think there might be a few usability issues at the root of this:

* Because the package is called RustEnhanced, when I hit Cmd+Shift+P, I expected things to work when I select "Build With: RustEnhanced". I didn't even think to look for Cargo.
* Same for the Build System -- I looked for Rust, not for Cargo.
* It's hard to know if you're using the built-in Rust support or the RustEnhanced plugin for many of the commands.

I wonder if "rustc without Cargo" is really at all a popular mode of compiling Rust code. It seems to me that almost everyone would be using Cargo these days. So perhaps we should be steering people towards the Cargo build option as a default.

**Comment by ehuss** [comment]
I noticed there are duplicated build variants if you have both Rust Enhanced and the stock Sublime "Rust" package enabled.  I ran the command "Package Control: Disable Package" and disabled the stock Rust package, and that seemed to solve things.

**Comment by Jayflux** [comment]
@joliss  is this still an issue?

**Comment by joliss** [comment]
I think it's mostly a usability issue. The "Automatic" build system works fine, but if I select "RustEnhanced" (which is the one I'd expect to use after installing this package), it fails because it tries to call rustc. Also there are 2 Cargo build systems, and I'm not sure which is the right one.

**Comment by Jayflux** [comment]
@joliss running rustc sounds correct to me, what else should it be running?
What is it you're trying to do? Then maybe i can tell you which command it is you need.

If its Cargo you want, then you have that option too, but by default it will just call rustc on your file.

Could you take a screenshot of the 2 Cargo build systems?

**Comment by joliss** [comment]
I didn't even have it on my radar that you could run rustc in isolation. I just assumed everything would go through Cargo in Rust-land. So I was very confused by the error message and didn't even realize it wasn't using Cargo.

Here's a screenshot of the 2 Cargo build systems:

<img width="884" alt="sublime screenshot" src="https://cloud.githubusercontent.com/assets/524783/23369679/0e69f08e-fd0a-11e6-882f-6fe78b0a5e49.png">

**Comment by Jayflux** [comment]
@joliss 
You almost never need to change build systems (Sublime will do this for you if you hit a rust or cargo file) and you almost never need to set it to to Cargo (thats a build system built into Sublime).

Just leave it set to RustEnhanced or Automatic, then use cmd+shift+B to pick the build you want, once you're happy with it sublime will remember your choice and you can do cmd+b from then on.

<img width="894" alt="screen shot 2017-02-27 at 17 11 47" src="https://cloud.githubusercontent.com/assets/936006/23371407/f43db488-fd0f-11e6-9571-4b96e3e23f07.png">

Does that clear up this issue?

**Comment by joliss** [comment]
Thanks!
