### ISSUE TITLE
Tokenization on boxed closure is not correct

### ISSUE THREAD

**Issue by speedcell4** [rust-lang/sublime-rust#144]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
v1.1.1

### Operating system
OS Name	macOS
Version	10.12.3 (16D32)

### Expected behavior
![qq20170213-231018](https://cloud.githubusercontent.com/assets/3585459/22886655/223025f2-f242-11e6-8f58-6ccbb2c8f8bd.jpg)
`->` should not be red

**Comment by Jayflux** [comment]
More info:
