### ISSUE TITLE
Build phantoms show file location shown instead of error message

### ISSUE THREAD

**Issue by ErichDonGubler** [rust-lang/sublime-rust#154]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
v1.2.1

### Operating system
Microsoft Windows 10 
10.0.14393 Build 14393.577

### Expected behavior
Phantoms shown like in the [Sublime Text blog]():

![](https://www.sublimetext.com/blog/images/build_error.png)

### Actual behavior
Instead, we get:
![image](https://cloud.githubusercontent.com/assets/658538/23179023/b924c5f2-f829-11e6-85ae-2371f488a012.png)

### Steps to reproduce
1. Make a new project (e.g., with `cargo new --bin`)
2. Modify the `Hello, world!` default `main.rs` to have some invalid syntax. In our example, let's do this:
    ```rust
    fn main() {adsf
        println!("Hello, world!");
    }
    ```
3. Observe as the phantoms show the file name

![image](https://cloud.githubusercontent.com/assets/658538/23179267/84269f32-f82a-11e6-84be-36c26211a890.png)

**Comment by dten** [comment]
What version of rust are you using?

**Comment by ErichDonGubler** [comment]
@dten:
`nightly-x86_64-pc-windows-msvc: rustc 1.17.0-nightly`
`stable-x86_64-pc-windows-msvc: rustc 1.15.1`

**Comment by dten** [comment]
Oh wait this one is easier than I first thought.

Those messages for from Sublime, not this plugin
The style below is from this plugin. The style in your pictures are from the sublime setting `"show_errors_inline"`
![image](https://cloud.githubusercontent.com/assets/1019038/23185137/3b0e4f20-f87a-11e6-8331-d21812a8b1c9.png)

**Comment by Jayflux** [comment]
Will see if i can replicate this this weekend
