### ISSUE TITLE
RustEnhanced Run not working on Windows 10

### ISSUE THREAD

**Issue by Jayflux** [rust-lang/sublime-rust#157]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
v1.2.2

### Operating system
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393

### Expected behavior
When running `RustEnhanced Run` i expect the plugin to run my binary

### Actual behavior
Its failing because its not falling into the windows setting (bizarre)

### Steps to reproduce
1. Create a simple "hello world" rust file
2. Compile it with RustEnhanced (in the build systems)
3. Call `RustEnhanced Run` and see if it runs

### Screenshot
The screenshot clearly shows that it should be running the binary as `test.exe`
but instead (look in the output) its running `./test`
Is this happening for anyone else? Is sublime broke? Our plugin or my sublime thinks its linux/mac for some reason?
![rustenhancedfailing](https://cloud.githubusercontent.com/assets/936006/23318845/0838374c-facc-11e6-9bf3-05b24803ec19.png)

**Comment by Vlad-Shcherbina** [comment]
I think it's a bug in [RustEnhanced.sublime-build:17](https://github.com/rust-lang/sublime-rust/blob/a7ff89729e94d2bcf5bb343ad6d0a211ac16c34a/RustEnhanced.sublime-build#L17).
By default the command is specified using `shell_cmd`, but the Windows version overrides `cmd`, leaving `shell_cmd` intact.

However, `shell_cmd` takes precedence over `cmd` when both are specified
(http://docs.sublimetext.info/en/latest/reference/build_systems/exec.html).

Possible solution would be to use something like this instead:
```json
            "windows":
            {
                "shell_cmd": "\"$file_base_name.exe\""
            }
```
