### ISSUE TITLE
Syntax error checking incorrect

### ISSUE THREAD

**Issue by ethe** [rust-lang/sublime-rust#161]
![image](https://cloud.githubusercontent.com/assets/12211036/23369075/13d240b2-fd4b-11e6-8ce1-581bfc8e208a.png)

The above program can be compiled no error, but syntax highlighting gives me an incorrect result. I have to rewrite it to `let funcs: Vec<Box<(Fn(_) -> _)>> = vec![foo, bar];` to bypass syntax checking.

**Comment by ethe** [comment]
And this case still mismatches highlighting rules:
 
![image](https://cloud.githubusercontent.com/assets/12211036/23369943/f8857ba0-fd4d-11e6-94ef-9c6f7cbd9160.png)

**Comment by Jayflux** [comment]
@ethe I don't get an error on either of those on the latest.
v1.2.6 may solve this, certainly the first issue for sure. https://github.com/rust-lang/sublime-rust/milestone/1

**Comment by ethe** [comment]
I upgraded it and problem solved, thanks.
