### ISSUE TITLE
Add build variant for `cargo check`?

### ISSUE THREAD

**Issue by ErichDonGubler** [rust-lang/sublime-rust#162]
Feature request to build on the great work! For CLI users, it's fairly common to run `cargo check` on a project to just run through the compile-time checks for code, instead of continuing to the code generation phase (which right now is less-than-optimal in Rust, in terms of speed). It would be nice to have this more accessible with the build variants packaged with this wonderful enhancement.

I don't foresee any significant additions to the build languages or anything else -- just an entry to the `variants` array in build definitions.

**Comment by Jayflux** [comment]
This has been released
https://github.com/rust-lang/sublime-rust/releases/tag/v1.3.0
