### ISSUE TITLE
Syntax highlighting broken for closures with tuple parameters.

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/sublime-rust#164]
| System or Software | Version |
|--|--:|
| Sublime Text | Build 3126 |
| Rust Enhanced | 1.2.3 |

Having code such as
```rust
let f = |(x, y)| { x + y };
```
results in broken syntax highlighting, where only the `x` in the `|(x, y)|` is highlighted,
but not the `y`. Of course, same with more than two parameters.
Also the two pipes are highlighted differently. With my settings the first is white while the second is yellowish.

This bug also happens with various uses of clojures. For example in this code too:

```rust
let sum = iterA
	.zip(iterB)
	.map(|(a, b)| foo(a, b)) // broken here!
	.sum();
```

**Comment by Jayflux** [comment]
Will take a look into this, i think dten did some work on improving tuple parsing, so will see what i can strip out from his PR
