### ISSUE TITLE
RustEnhanced suddenly stops highlighting of code mid-code (with image)

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/sublime-rust#175]
| System or Software | Version |
|--|--:|
| Sublime Text | Build 3126 |
| Rust Enhanced | 1.2.3 |

An image for the problem:
http://i.imgur.com/OK7WNVe.png

I cannot tell how this happens exactly.

**Comment by Jayflux** [comment]
@Robbepop could you try running this on the latest version, also could you put a gist link of that code in here, so we can test it our end.
Thanks

**Comment by Robbepop** [comment]
The code I was operating on can be found [here](https://github.com/bluss/rust-ndarray/blob/master/src/iterators/mod.rs#L941).
Keep in mind that this is a very actively mutated piece of code and so the break-point of the syntax highlighting could be somewhere else now.

**Comment by Jayflux** [comment]
I am able to reproduce this on 1.3.0
Will take a look into it, thanks for the code sample

**Comment by Jayflux** [comment]
@Robbepop I've fixed it in this release
https://github.com/rust-lang/sublime-rust/releases/tag/v1.3.1

GIve it a try and let me know

**Comment by Robbepop** [comment]
fixed for me, too. :)

thanks for the fast bug fix!
