### ISSUE TITLE
Is it possible to run cargo build from opened Cargo.toml?

### ISSUE THREAD

**Issue by pravic** [rust-lang/sublime-rust#179]
Currently I need to open some .rs file to access Cargo build commands from Sublime despite of I already have Cargo.toml file opened.

Quick search pointed me to the [selector property](http://sublimetext.info/docs/en/reference/build_systems.html) of build description. Is it possible to place 2 selectors there, like `source.rust|source.toml`?

Currently as a workaround I copied _Cargo.sublime-build_ as _CargoToml.sublime-build_ with `source.toml` selector in there, because it seems that "_Build System -> Cargo_" command is global-wide in Sublime, not syntax-specific.

### Sublime Text Version
Sublime Text 3 (Build 3131)

### Rust Enhanced Version
1.3.1

**Comment by pravic** [comment]
cc #165 - it would be great to have such feature there.

**Comment by ehuss** [comment]
Another workaround is to not use the "Automatic" build detection.  In Tools > Build System, pick the build system to use, and it will be sticky (saved in the workspace).

**Comment by pravic** [comment]
> saved in the workspace

Which one workspace?

**Comment by ehuss** [comment]
@pravic The `.sublime-workspace` file contains the current state of your project (which files are open, etc.).  If you save a sublime-project, it automatically also saves a workspace.  See https://www.sublimetext.com/docs/3/projects.html for more info.

@Jayflux I think you can have multiple selectors with a comma (such as "source.rust,source.toml").
