### ISSUE TITLE
-Z no-trans support going away soon

### ISSUE THREAD

**Issue by ehuss** [rust-lang/sublime-rust#183]
As of rust-lang/rust/pull/41751 -Z options are available on nightly only.  This means that on-save syntax checking will stop working once this lands on beta/stable channels if you are using those toolchains.  #165 already has support for `cargo check` and `clippy`, but it still defaults to `-no-trans`.  

I will look into auto-detecting the rustc version and choosing either `no-trans` or `cargo check` based on what's available (I'm not sure how much of a performance impact that will have).  This will also probably warrant some notes in the docs, since this will result in a loss of functionality (particularly `rust_syntax_checking_include_tests`).

**Comment by Jayflux** [comment]
Since your changes would bring a breaking change release anyway, should we not just move it to cargo check and tell people to upgrade to the latest rust if they want that feature. I think this would be easier than detecting their version.

**Comment by ehuss** [comment]
Sounds good to me.  I was uncertain how quickly the average user upgrades their compiler, but the workaround (switching the config) is easy.

**Comment by Jayflux** [comment]
@ehuss im guessing we can close this issue now?

**Comment by ehuss** [comment]
I neglected to switch the default from -Zno-trans to "cargo check" in the branch on github.  I just pushed a PR to switch the default, which will be required for 1.19.
