### ISSUE TITLE
Cargo build system fails

### ISSUE THREAD

**Issue by Fireforge** [rust-lang/sublime-rust#19]
When I try to Build or Run using the Cargo build system, the status bar says "Building" but nothing shows up on the console.
Commenting out the "syntax" specification (line #4 in the Cargo.sublime-build file) fixes the issue, at least on my system.

Environment:
Windows 7 64-bit
rustc 0.12.0-nightly (740905042 2014-09-29 23:52:21 +0000)
cargo 0.0.1-pre-nightly (2d101e2 2014-10-09 19:44:57 +0000)
Sublime Text 2 Version 2.0.2, Build 2221

**Comment by Jayflux** [comment]
We no longer support Sublime Text 2, and i think this problem may have been resolved by now
