### ISSUE TITLE
2.0 no longer compatible with Comments-Aware Enter

### ISSUE THREAD

**Issue by mistydemeo** [rust-lang/sublime-rust#195]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
2.0.1

### Operating system
A good example is:
OS Name	macOS
Version	10.12.6 (16G29)

### Description
The Rust Enhanced syntax no longer seems to be compatible with the [Comments-Aware Enter](https://github.com/Suor/CommentsAwareEnter) package.

### Steps to reproduce
1. Set syntax to "Rust Enhanced".
2. Install Comments-Aware Enter.
3. Create a comment.
4. Hit "enter" while on the line with the comment.

### Expected behavior
The next line automatically begins with `// `.

### Actual behavior
The next line does not automatically begin as a comment.

**Comment by dten** [comment]
hey I can't reproduce the error. looking at the plugin's source it looks for comment.line at the start of the scope. Nothing changed with the scopes between  v1.3.1 and v2.0.0, it was all the build system.
Can you go to the point you're pressing enter in your comment and press `cmd + alt + shift + p` to show the scopes and send a screenshot of what it's showing

**Comment by mistydemeo** [comment]
Looks like it's different depending on whether I'm at the end of the line or not:

<img width="475" alt="screen shot 2017-07-22 at 2 09 08 pm" src="https://user-images.githubusercontent.com/780485/28494588-9cfa20a4-6ee7-11e7-88ae-bf5d5cb4de8e.png">

<img width="636" alt="screen shot 2017-07-22 at 2 11 35 pm" src="https://user-images.githubusercontent.com/780485/28494597-b2899508-6ee7-11e7-8ba8-e63e58b400a0.png">

**Comment by dten** [comment]
C# (for example) syntax includes the new line
https://github.com/sublimehq/Packages/blob/master/C%23/C%23.sublime-syntax#L66
Rust, and a few others i tried don't

I've done a PR to extend it to include the new line which then makes enter on the end of the line continue the comment
https://github.com/rust-lang/sublime-rust/pull/196

**Comment by mistydemeo** [comment]
Thank you!
