### ISSUE TITLE
Shortcut to hide phantoms ?

### ISSUE THREAD

**Issue by kamek-pf** [rust-lang/sublime-rust#200]
Is it possible to bind a key to hide the inline erros ?
I tried this :
```
{
    "keys": ["ctrl+l"],
    "command": "exec",
    "args": {
        "hide_phantoms_only": true
    },
    "context": [
        { "key": "setting.command_mode" }
    ]
}
```

but it doesn't seem to do anything (ST3 build 3126).

**Comment by ehuss** [comment]
I'll add a command.  Would it be okay if it toggles the visibility on/off instead of just turning them off?

**Comment by kamek-pf** [comment]
Ideally, the shortcut would just dismiss them.

By dismiss I mean the same thing that is currently happening when you close
a phantom using the X button (they all go away, regardless of which one was
clicked).

This behavior would be a lot more beginner friendly.
You'd be able to save a file, likely see the whole screen turn red, press
something like `esc` to dismiss the phantoms, fix the first error and try
again.

Thanks for looking into this !

**Comment by Jayflux** [comment]
@ehuss has this been added with your latest update

**Comment by ehuss** [comment]
Not yet.  I have a separate local branch where I was toying with this.  I'll push a PR soon.
