### ISSUE TITLE
Next Result / Previous Result (F4 / Shift + F4) don't work when "show_errors_inline" is false

### ISSUE THREAD

**Issue by madadam** [rust-lang/sublime-rust#206]
Some people might prefer to disable inline errors (myself included), but that breaks the "Next Result" and "Previous Result" commands. My guess is that it happens because the non-inline error output doesn't conform to the pattern that Rust Enhanced expects. 

This is how the error output looks like:
```
error[E0425]: cannot find function `helo` in this scope
 --> src/main.rs:3:5
  |
3 |     helo()
  |     ^^^^ did you mean `hello`?
```
Problem is probably the `-->` thing at the beginning of the line.

I was trying to fix this by adding a custom `file_regex` entry to `Rust Enhanced.sublime-build`, but it didn't work because the custom command used (`cargo_exec`) doesn't recognize that option.

**Comment by ehuss** [comment]
Thanks for the report.  I have a fix, and I'll post a PR soon.  There are a few other issues and I want to make sure they are taken care of.
