### ISSUE TITLE
Ligature support

### ISSUE THREAD

**Issue by kamek-pf** [rust-lang/sublime-rust#216]
Sublime added ligature support in [build 3146](http://www.sublimetext.com/3dev).
Using FiraCode, here's what happens in Rust sources :
![ss](https://user-images.githubusercontent.com/3883992/31504122-8feb6204-af3f-11e7-8a1b-e52cf5ffa6aa.png)

Ligatures work fine in other languages, and as someone pointed out in [this discussion](http://sublimetext.userecho.com/topics/4719-does-sublimetext-support-programming-ligatures-fontlike-fira-code/?comment_form_activate=true), we might want to look into the syntax definition itself.

### Sublime Text Version
Sublime Text 3 (Build 3147)

### Rust Enhanced Version
v2.2.0

### Operating system
Arch

### Expected behavior
Ligatures should work everywhere

### Actual behavior
Some ligatures aren't applied

**Comment by dten** [comment]
Looks like the pattwrn below would match the `!` separately from the `=`
```
   - match: '\.\.\.|\.\.||[-=<>&|!~@?+*/%^''#$]|\b_\b'
      scope: keyword.operator.rust
```

I can sort it but i can't even figure out how to show ligatures 😅

**Comment by kamek-pf** [comment]
I didn't do anything special to make them work, they just showed up after the upgrade.
Make sure your build is 3146 or newer and use a font that support ligatures '_'

3146 is in the dev branch btw, stable is stuck at 3143

**Comment by dten** [comment]
manged to enable FiraCode and fixed it, PR pending
https://github.com/rust-lang/sublime-rust/pull/217
