### ISSUE TITLE
Build using Cargo

### ISSUE THREAD

**Issue by dutt** [rust-lang/sublime-rust#22]
I added a new issue for this seems it seems to be a different cause.

ST 3, Rust plugin, tried building using Cargo and I got this:
```
[Errno 2] No such file or directory: 'cargo'
[cmd: ['cargo', 'build']]
[dir: /Users/dutt/workspace/rust/gridwar/src/entities]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]
```

Which is understandable, since I get this:
```
dutt$ which cargo
/usr/local/bin/cargo
```

How do I edit the path used by the plugin?

**Comment by rowlandrose** [comment]
Thanks @hughes ! I ran into the same problem on my Mac and that worked perfectly.

**Comment by pzol** [comment]
Using rustup.rs I added 

    "env": {
        "PATH": "$HOME/.cargo/bin:$PATH"
    },

**Comment by Jayflux** [comment]
Since moving to rustup this has stopped working for me.
Can we add the Home path by default?

**Comment by Jayflux** [comment]
This has been fixed in https://github.com/rust-lang/sublime-rust/pull/97
