### ISSUE TITLE
`fn` not highlighted for function pointer types

### ISSUE THREAD

**Issue by aldanor** [rust-lang/sublime-rust#34]
For example:
```rust
Option<extern "C" fn (c_int)>
```
`fn` is not highlighted as keyword (and if there is no space before the opening parenthesis, it's erroneously highlighted as an identifier).

**Comment by petrochenkov** [comment]
Fixed by https://github.com/rust-lang/sublime-rust/pull/65

**Comment by Jayflux** [comment]
@aldanor closing
