### ISSUE TITLE
Nested block comments

### ISSUE THREAD

**Issue by contradictioned** [rust-lang/sublime-rust#41]
Hey, I just found, that Rust [supports](https://doc.rust-lang.org/reference.html#comments) nested block comments like

    /* a comment /* within a comment */ that's cool */

But the part `that's cool */` is highlighted as if it was code. (Don't know if this is even possible to accomplish with Sublime's syntax definitions, a very quick google search didn't find anything)

**Comment by rprichard** [comment]
I think it's possible to fix this.  The plugin is already doing the right thing with nested doc-style comments.  e.g.:
```
/** 1
/** 2
*/ 3
*/ 4
fn main() {}
```
Notice how `rust_comment_doc_block` is implemented [here](https://github.com/jhasse/sublime-rust/blob/7da22dbb3a1ce10b328c33b25ec5349f263b8b5c/Rust.JSON-tmLanguage#L148) versus how `comment.block.source.rust` is implemented [here](https://github.com/jhasse/sublime-rust/blob/7da22dbb3a1ce10b328c33b25ec5349f263b8b5c/Rust.JSON-tmLanguage#L87).

**Comment by petrochenkov** [comment]
Fixed by https://github.com/rust-lang/sublime-rust/pull/65

**Comment by Jayflux** [comment]
@contradictioned merged and closing
