### ISSUE TITLE
Associated type breaks function declaration highlighting -- fn foo<T: Iterator<Item=i32>>(x: &T) {}

### ISSUE THREAD

**Issue by rprichard** [rust-lang/sublime-rust#42]
The function declaration `fn foo<T: Iterator<Item=i32>>(x: &T)` isn't highlighted like a function declaration.  The `Item=i32` associated type constraint is throwing it off.

![test](https://cloud.githubusercontent.com/assets/1572855/6913074/b9575d0e-d72f-11e4-9438-1ac0ebe1e086.png)

**Comment by petrochenkov** [comment]
Fixed by https://github.com/rust-lang/sublime-rust/pull/65

**Comment by Jayflux** [comment]
@rprichard merged and closing
