### ISSUE TITLE
Attributes and comments have the same highlighting

### ISSUE THREAD

**Issue by yberreby** [rust-lang/sublime-rust#51]
...which probably shouldn't be the case since attributes have a semantic meaning, unlike comments. They often come out greyed out and hardly readable, such as in Solarized Dark.

**Comment by Jayflux** [comment]
@yberreby I agree, i will see if i can do a quick PR which adds some semantics to attributes

**Comment by wbond** [comment]
This is one area that hasn't really had any movement on terms of coming up with [standardized scopes](http://www.sublimetext.com/docs/3/scope_naming.html) for.

Currently the standard C# syntax doesn't add anything but `meta` scopes. Python decorators add a `meta` scope and a scope on the leading `@`.

Java hasn't seen a rewrite yet, but it is currently using `storage.type.annotation` for the `@` and the identifier. In general `storage.type` is rather over-used in the various syntaxes, so Ideally we can come up with something better than that.

**Comment by Jayflux** [comment]
@wbond  so what do you reckon we should go with for the time being?

**Comment by Jayflux** [comment]
This is being addressed here:
https://github.com/sublimehq/Packages/issues/709

**Comment by Jayflux** [comment]
Looks like there's been a decision in the sublimehq issue, but i don't know when these changes take affect.

Once they do ill happily update the syntax parsing on our side

**Comment by wbond** [comment]
I don't believe there is anything for us to do in core, really. We mostly just decided on a standard for the scope names. They will be added to the scope naming docs, but I don't recall needing any changes to Monokai. Other color schemes can start using those scope names, and the standard syntaxes will be updated to those scope names as work is done on them.

*In general, right now, we aren't maintaining or making changes to any of the color schemes other than Monokai. The other ones are likely to be officially deprecated with Sublime Text 3 stable.*

**Comment by Jayflux** [comment]
@wbond ok, so does this mean that an annotation or an attribute will visually look the same as a comment?
Because if there's no changes to Monokai then i'm guessing we won't see any styling to annotations

let me know if i've got it wrong

**Comment by wbond** [comment]
No, the recommendation does not recommend using any `comment.` scopes, except if comments are embedded in the attribute.

Basically, the scope names applied to attributes/annotation need to change. https://github.com/sublimehq/Packages/issues/709#issuecomment-266835130 outlines what they should be.

**Comment by Jayflux** [comment]
> No, the recommendation does not recommend using any comment. scopes, except if comments are embedded in the attribute.

@wbond sure i get that, i mean once i change the comments to annoations/attributes, will i see any visual difference in the built-in Monokai theme? Or will it look the same as a comment?

**Comment by wbond** [comment]
It will look completely different. The only thing in Monokai that is styled with the dark grey is comments. Monokai does not apply any colors to annotations, so the annotation tokens will look as they would in any other Rust context.

**Comment by Jayflux** [comment]
Ok thanks for clearing that up, I will get started on this change then!

**Comment by Jayflux** [comment]
Released
https://github.com/rust-lang/sublime-rust/releases/tag/v1.3.0
