### ISSUE TITLE
Navigation in text (up/down/left/right) becomes sluggish when Rust syntax highlighting enabled

### ISSUE THREAD

**Issue by 315234** [rust-lang/sublime-rust#54]
Performance is notably worse than with a non-syntax highlighted file, and compared to other syntax highlightings.

**Comment by jhasse** [comment]
I can't confirm this, although it's been a while since I last used Sublime Text. See #55

**Comment by petrochenkov** [comment]
Can't confirm

**Comment by Jayflux** [comment]
@315234 I can't confirm this either, could you tell us your Sublime version, OS version etc
Thanks

**Comment by Jayflux** [comment]
Closing
