### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by jhasse** [rust-lang/sublime-rust#55]
I have switched to Atom for developing in Rust. Therefore would be great if someone else wants to maintain this package :)

**Comment by sailorswift** [comment]
I would be willing to do this and can start working on some of the issues this week.

**Comment by jhasse** [comment]
Great! Should I transfer the ownership of this repro to you (to preserve the issues) or do you want to fork?

You'll also need to create a PR like this: https://github.com/wbond/package_control_channel/pull/2607

**Comment by gbersac** [comment]
Why not giving it back to the rust community ? The best idea could be to transfer ownership to the [rust programming language github organization](https://github.com/rust-lang). Emacs and vim rust plugin are already hosted there.

 Ask on [reddit](https://www.reddit.com/r/rust/), [on the rust forum](https://users.rust-lang.org/).

**Comment by jhasse** [comment]
Good idea! I've posted on reddit: https://www.reddit.com/r/rust/comments/3iygku/transfer_the_ownership_of_sublimerust_to_rustlang/

**Comment by gbersac** [comment]
Great ! I posted there.

**Comment by gbersac** [comment]
@jhasse please add [Steve Klabnik](https://github.com/steveklabnik) as owner of this repository, he will take care of the transfer like he said [here](https://www.reddit.com/r/rust/comments/3iygku/transfer_the_ownership_of_sublimerust_to_rustlang/cukuvvu).

**Comment by petrochenkov** [comment]
I'm going to fix bugs here, but I'm not sure how publishing to Package Control happens and things like that

**Comment by gbersac** [comment]
@petrochenkov just update the repository, package control will download the latest version of this github repository every time someone ask for this package.

**Comment by petrochenkov** [comment]
Now I see, the package is updated on Package Control.
The only thing I don't like there is the label `ST2/ST3`, because the package is supposed to work on ST3 (personally, I've never tried it on ST2, does it works there at all?).

**Comment by gbersac** [comment]
Should be close ?

**Comment by jhasse** [comment]
@petrochenkov Some stuff doesn't work in ST2 (for example the syntax highlighting of the build output).

@gbersac Yes, thx
