### ISSUE TITLE
Improve rust symbol define

### ISSUE THREAD

**Issue by gbersac** [rust-lang/sublime-rust#61]
Currently only the functions are defines as symbol (you can see them by using ctrl+r or ctrl+shift+r). It could be great to have function and [struct/enum] and functions.

so the following code :

``` rust
struct Aaa {
    field1: i32,
}

impl Aaa {
    pub fn new (f1: i32) -> Aaa {
        // code here
    }

    fn another_fn() {
        // code here
    }
}

impl Display for Aaa
{
    fn fmt(&self, f: &mut Formatter) -> Result<(), Error> {
        // code here
    }
}
```

would be converted, on the goto symbol pallet :

```
struct Aaa
impl Aaa
    new
    another_fn
impl Display for Aaa
    fmt
```

**Comment by Jayflux** [comment]
@gbersac  will try and look into this when i get time

**Comment by wbond** [comment]
These should all be handled by ST's default Rust syntax, which @Jayflux just merged the syntax portion of into this repo. Additionally, the preferences files containing the scopes to include in the symbol list and index would need to be added.

**Comment by Jayflux** [comment]
Yeah it needs some tidying up i think, however struct is now being picked up as a symbol

**Comment by Jayflux** [comment]
looks like @dten's PR fixes this
https://github.com/rust-lang/sublime-rust/pull/116

**Comment by dten** [comment]
very much work in progress though

**Comment by Jayflux** [comment]
This has been fixed/improved with https://github.com/rust-lang/sublime-rust/pull/141
please raise an issue if this is still a problem
