### ISSUE TITLE
create temp file automatically

### ISSUE THREAD

**Issue by xqskyx** [rust-lang/sublime-rust#64]
when I edit rs file, sublime create a lot of temp file .menu tree like this
(fail to upload a picture :( ):
main.rs
tmp9tzn72
tmpaeu3zy
tmphhg8wt
tmprjw53i
tmpurpnft
tmpv63r4d
but when I edit other kinds of files,such as py and html,there is no temp file made;
so I afraid that I can do something with the sublime-rust settings.

**Comment by petrochenkov** [comment]
These files are known to be created by RustAutoComplete when something is wrong with racer, not Rust package.
This issue can probably be closed.
