### ISSUE TITLE
faild to build any rust source code

### ISSUE THREAD

**Issue by zsynacl** [rust-lang/sublime-rust#66]
After I pressed ctrl+B or click the menu `compile`, nothing happend.
I checked the Rust.sublime-build, the file content was written like this
`selector:source.rust`
Is it a correct form? or I should change it to `source.rs`?
Also, how can I use cargo as a compile and run tool?
looking forward to any solution

**Comment by diaphore** [comment]
The `source.rust` selector refers to the one defined in [`Rust.tmLanguage`](https://github.com/rust-lang/sublime-rust/blob/master/Rust.JSON-tmLanguage#L3). You might need to specify `Cargo` or `Rust` in `Tools > Build System`.

**Comment by Jayflux** [comment]
@zsynacl 
I'm closing this issue, please re-open if you're still having this problem
