### ISSUE TITLE
`self` keyword is not highlighted

### ISSUE THREAD

**Issue by sdleffler** [rust-lang/sublime-rust#67]
For example, given a function
```
fn distance(self, other: Vec3f) -> f64 {
    (self - other).length()
}
```
`self` does not appear highlighted as other keywords would.

**Comment by petrochenkov** [comment]
This is not accidental, `self` is highlighted as a variable and `Self` as a type.
I remember coloring them as keywords and it looked pretty bad.

**Comment by sdleffler** [comment]
Mm, I see. It caused me some confusion as the compiler's error messages do state that "self" is a keyword. I'll close this issue then. Thank you for the clarification.
