### ISSUE TITLE
Can we add a rust & run (which builds and runs) similar to go run in Golang?

### ISSUE THREAD

**Issue by Jayflux** [rust-lang/sublime-rust#73]
This would make learning rust much faster.
At the moment every change i make i need to run cmd + B - Rust, then cmd + B - Run 
could we have one which runs the 2 so i can just run 1 build in sublime which does both?

So we have functionality similar to go run?

Thanks

**Comment by dten** [comment]
My top tip to you is use Cargo :) doc.crates.io/guide.html

**Comment by Jayflux** [comment]
@dten for projects sure!
I'm talking more about having a playground to dump code in and see if it works without having to set up any project or file structure. I do this quite a lot with other languages when i want to try some syntax out
Similar to https://play.rust-lang.org/ except in Sublime

**Comment by lloydac** [comment]
An easy way to do this would be to use [cargo-script](https://github.com/DanielKeep/cargo-script). Just install it and then set up a build command that passes the name of the file to `cargo script`.

**Comment by Jayflux** [comment]
Thanks @lloydac playing with that now, would be nice if there's some way of integrating that

**Comment by Jayflux** [comment]
Cargo Script has now been added. So i'm going to close this
