### ISSUE TITLE
Build error messages are not persisted when Cargo - Build command is run multiple times

### ISSUE THREAD

**Issue by sekjun9878** [rust-lang/sublime-rust#75]
Hello,

Due to this bug: https://github.com/rust-lang/cargo/issues/2494 when the Build command is given multiple times the error messages are not persisted.

This can be worked around by running `cargo clean` prior to building.

**Comment by Jayflux** [comment]
@dten what are your thoughts on this?

**Comment by Jayflux** [comment]
@sekjun9878 are you still getting this problem on the latest version of Rust Enhanced?

**Comment by sekjun9878** [comment]
@jayflux I haven't used Rust for quite a while, so I'm not too sure on the current state of things.

**Comment by Jayflux** [comment]
Closing this, please re-open if you're still experiencing this on 2.0.0
