### ISSUE TITLE
'let mut' snippet

### ISSUE THREAD

**Issue by BjornMelgaard** [rust-lang/sublime-rust#76]
please, add `letm.sublime-snippet`

``` xml
<snippet>
    <content><![CDATA[let mut ${1:pat} = ${2:expr};]]></content>
    <tabTrigger>letm</tabTrigger>
    <scope>source.rust</scope>
    <description>let mut … = …;</description>
</snippet>
```

**Comment by Jayflux** [comment]
@BjornMelgaard  could you do this as a PR?

**Comment by Jayflux** [comment]
https://github.com/rust-lang/sublime-rust/pull/123

**Comment by Jayflux** [comment]
@BjornMelgaard  this has now been released
https://github.com/rust-lang/sublime-rust/releases/tag/v1.0.2

**Comment by BjornMelgaard** [comment]
@Jayflux thanks for attention
