### ISSUE TITLE
make a lot of tmp files that is code snippet

### ISSUE THREAD

**Issue by ljun51** [rust-lang/sublime-rust#79]
<img width="228" alt="tmp" src="https://cloud.githubusercontent.com/assets/5824240/14100489/70b306a6-f5c0-11e5-9a88-66d542de4a15.png">

**Comment by dten** [comment]
The Rust auto complete package makes these

**Comment by erkentus** [comment]
Same issue here, how to solve it?

**Comment by samlet** [comment]
Disable Rust auto complete package will solve it.

**Comment by lramirez98** [comment]
In case your still having the issue there is a fix here https://github.com/defuz/RustAutoComplete/issues/19
Your just need to specify the full path to racer in the settings for RustAutoComplete

**Comment by Jayflux** [comment]
If this issue is not coming from this package then i'm closing the ticket
