### ISSUE TITLE
Snippets from other editors

### ISSUE THREAD

**Issue by RustSnippets** [rust-lang/sublime-rust#80]
https://github.com/zargony/atom-language-rust/blob/master/snippets/rust.cson
https://github.com/abaez/ta-rust/blob/master/snippets.lua
https://github.com/freebroccolo/rust-snippets/blob/master/rust-snippets.el
https://github.com/darookee/vim-snippets/blob/master/UltiSnips/rust.snippets

Maybe you can add the missing snippets from other editors and implement it in your project.

**Comment by Jayflux** [comment]
That's a big list, I think we'll add them as they're requested.
So i'm closing this issue for now.
