### ISSUE TITLE
Possible Rust error format updates and IDE support

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/sublime-rust#84]
Hi all,

Sorry to use the issue tracker as a message box, but I wanted to mention that we're working on a possible update to the compiler error output: https://github.com/rust-lang/rfcs/pull/1644  This might have an impact on the sublime plugin if you all happen to be parsing the compiler output.

That said, we're also thinking about standardizing a JSON format, so IDEs can get more information from the compiler (and not have to parse the error).

Would love to chat and hear your thoughts.

**Comment by jonathandturner** [comment]
Just to follow-up here, we're discussing making the switch to new errors soon: https://github.com/rust-lang/rust/pull/35401.  Once the switch is made, there are still some weeks before it shows up in a stable release, which hopefully gives us time to make the transition as smooth as possible.

If this impacts you, please let us know.

**Comment by c0gent** [comment]
#85 fixes the plugin to work with the new error messages.

@brson or @steveklabnik, are you the ones we should bug to get this merged?

**Comment by Thinkofname** [comment]
Posted #87 as an attempt of support `--error-format=json` to display the errors

**Comment by jonathandturner** [comment]
Great to see some progress here!

Friendly reminder - I'm going to each plugin just to let people know that we're 17 days away from the Rust 1.12 release, where the new error format will be the main format (and the old error format will be removed).

**Comment by Jayflux** [comment]
@jonathandturner https://github.com/rust-lang/sublime-rust/pull/87 is now merged and we now use it by default. So I'm guessing there's not much we have to do here?
We can probably close this ticket

**Comment by jonathandturner** [comment]
Sounds good.  Thanks all!
