### ISSUE TITLE
Rustup breaks this package

### ISSUE THREAD

**Issue by Jayflux** [rust-lang/sublime-rust#92]
Switching from brew to rustup causes this package to break
by default this package checks the typical paths /bin:/usr/bin etc but rustup puts rust in ~/.cargo/bin

I've tryed adding that folder for the path: but it doesn't seem to be working for me.
Would love to see if anyone can get this working

Rust build paths:
```json
    "osx":
    {
        "path": "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    },
```

When i try changing the path in https://github.com/rust-lang/sublime-rust/blob/master/Rust.sublime-build and reload the plugin, the path is still the same.

As you can see in the images, even though i add a new path to the end, it does not reflect when running the plugin. I've tried adding a lot of different paths.

<img width="815" alt="screen shot 2016-10-05 at 11 41 29" src="https://cloud.githubusercontent.com/assets/936006/19110263/e9515732-8af0-11e6-8a5c-a4ce3e458fcf.png">
<img width="527" alt="screen shot 2016-10-05 at 11 40 22" src="https://cloud.githubusercontent.com/assets/936006/19110268/efdcb7b8-8af0-11e6-83a5-d264f3d234f3.png">

Is this a bug within Sublime 3 itself? @FichteFoll @wbond
Build: 3125

Note:
This issue has also been mentioned in https://github.com/rust-lang/sublime-rust/issues/22

**Comment by wbond** [comment]
I don't believe `path` is a known variable for build systems.

With any luck, the next dev build of ST3 will actually have code to pull in your shell environment on OS X, which should resolve this issue.

**Comment by Jayflux** [comment]
Thanks for the quick response @wbond !
So I'm assuming path will just be the user's system path when running build? which means we can get rid of the path field here?

**Comment by FichteFoll** [comment]
@Jayflux see the `env` key described here: http://docs.sublimetext.info/en/latest/reference/build_systems/exec.html
Basically, 
```js
{
    ....
    "env": {
        "path": "$path:~/.cargo/bin"
    }
}
```

**Comment by Jayflux** [comment]
Apparently the path in the debug information is incorrect:
https://github.com/SublimeTextIssues/Core/issues/1039

**Comment by wbond** [comment]
Sorry, I was looking at the C++ part of the build system implementation… it does appear that through the kwargs in the `exec` build system that `path` should work. It does appear, however that it is not reflected in the build system output.

I'll try to get these edge cases cleaned up in one of the next builds.
