### ISSUE TITLE
Post-save error highlight doesn't work when project contains both main.rs and lib.rs

### ISSUE THREAD

**Issue by omakoto** [rust-lang/sublime-rust#94]
Looks like if a project contains both src/main.rs and src/lib.rs, post-save error highlight doesn't work.  If I run the cargo rustc command manually it just fails with the following error.

$ cargo rustc -- -Zno-trans -Zunstable-options --error-format=json
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target

I have to add either --lib or --bin for the rustc command to work.

$ cargo rustc --lib -- -Zno-trans -Zunstable-options --error-format=json # works
$ cargo rustc --bin [BIN-NAME] -- -Zno-trans -Zunstable-options --error-format=json #works

Also setting RUSTFLAGS with "cargo build" seems to work -- should the plugin switch to it??

$ RUSTFLAGS="--error-format=json" cargo build # this also seems to work

**Comment by Jayflux** [comment]
good spot @omakoto 
Not sure what the best fix for this would be, its a shame it can't just check both :/
if RUSTFLAGS works then maybe its easier to try that.

**Comment by omakoto** [comment]
Hmm, except, cargo build fails in one of my projects unless I remove "no-trans":
=========================================================
$ RUSTFLAGS="-Zno-trans -Zunstable-options --error-format=json" cargo build --verbose

Build failed, waiting for other jobs to finish...
error: could not rename crate "/home/omakoto/cbin/src/rust/highlighter-rs/target/debug/build/bzip2-sys-b768200d1597b521/build_script_build"

Caused by:
  No such file or directory (os error 2)
=========================================================
However "cargo rustc" works fine in the same project for both with --lib and --bin... :(

I guess it'd be too slow if you remove no-trans?

**Comment by Jayflux** [comment]
@nrc @dten what are your thoughts on this?

**Comment by nrc** [comment]
You should prefer RUSTFLAGS to cargo rustc, for sure.
